import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import "./globals.css";

import { Navbar } from "@/components/layout/navbar/Navbar";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <>
      <html lang={locale} suppressHydrationWarning>
        <head />
        <body className="min-h-dvh w-full flex flex-col">
          <NextIntlClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {/** Header */}
              <Navbar />

              <main
                className={`p-5 grid gap-5 auto-rows-fr flex-1`}
                style={{
                  gridTemplateColumns:
                    "repeat(auto-fit, minmax(clamp(200px, 20%, 300px), 1fr))",
                }}
              >
                {children}
              </main>

              {/** Footer */}
              <Footer />
            </ThemeProvider>
          </NextIntlClientProvider>
        </body>
      </html>
    </>
  );
}
